<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EditeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditeurRepository extends EntityRepository
{

}
